"""widen_shift_column

Revision ID: a0814ff50355
Revises: 0002
Create Date: 2026-07-08 13:27:50.654701
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = 'a0814ff50355'
down_revision: Union[str, None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('batches', 'operator',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('batches', 'scanner_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('batches', 'original_pdf_path',
               existing_type=sa.VARCHAR(length=1024),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('batches', 'ocr_version',
               existing_type=sa.VARCHAR(length=64),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('batches', 'ai_version',
               existing_type=sa.VARCHAR(length=64),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('batches', 'image_pipeline_version',
               existing_type=sa.VARCHAR(length=64),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('batches', 'factory_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('batches', 'plant_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('batches', 'line_name',
               existing_type=sa.VARCHAR(length=128),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('correction_log', 'ocr_value',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("''::text"))
    op.alter_column('correction_log', 'corrected_value',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("''::text"))
    op.alter_column('correction_log', 'operator',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('defect_library', 'category',
               existing_type=sa.VARCHAR(length=128),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('defect_library', 'component',
               existing_type=sa.VARCHAR(length=128),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('defect_library', 'manufacturer_context',
               existing_type=sa.VARCHAR(length=512),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('duplicate_log', 'operator',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('exports', 'created_by',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('inspections', 'page_number',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('inspections', 'batch_page_index',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('inspections', 'tractor_no',
               existing_type=sa.VARCHAR(length=64),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('inspections', 'tractor_model',
               existing_type=sa.VARCHAR(length=128),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('inspections', 'engine_no',
               existing_type=sa.VARCHAR(length=128),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('inspections', 'chassis_no',
               existing_type=sa.VARCHAR(length=128),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('inspections', 'inspector',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('inspections', 'shift',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.String(length=32),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('inspections', 'line_no',
               existing_type=sa.VARCHAR(length=32),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('inspections', 'verified_by',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('inspections', 'final_verified_by',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('inspections', 'raw_text',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("''::text"))
    op.alter_column('inspections', 'ocr_version',
               existing_type=sa.VARCHAR(length=64),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('inspections', 'ai_version',
               existing_type=sa.VARCHAR(length=64),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('inspections', 'image_pipeline_version',
               existing_type=sa.VARCHAR(length=64),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('inspections', 'image_path_original',
               existing_type=sa.VARCHAR(length=1024),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('inspections', 'image_path_enhanced',
               existing_type=sa.VARCHAR(length=1024),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('inspections', 'ocr_json_path',
               existing_type=sa.VARCHAR(length=1024),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('inspections', 'verified_json_path',
               existing_type=sa.VARCHAR(length=1024),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.drop_index(op.f('ix_inspections_needs_review'), table_name='inspections', postgresql_where='(needs_review = true)')
    op.drop_index(op.f('ix_inspections_status'), table_name='inspections')
    op.create_index('idx_inspections_needs_review', 'inspections', ['needs_review'], unique=False, postgresql_where=sa.text('needs_review = TRUE'))
    op.create_index('idx_inspections_status', 'inspections', ['status'], unique=False)
    op.drop_index(op.f('ix_learning_entries_raw_field'), table_name='learning_entries')
    op.drop_constraint(op.f('uq_raw_text_field'), 'learning_entries', type_='unique')
    op.create_index('idx_learning_entries_raw_field', 'learning_entries', ['raw_text', 'field'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_learning_entries_raw_field', table_name='learning_entries')
    op.create_unique_constraint(op.f('uq_raw_text_field'), 'learning_entries', ['raw_text', 'field'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_learning_entries_raw_field'), 'learning_entries', ['raw_text', 'field'], unique=True)
    op.drop_index('idx_inspections_status', table_name='inspections')
    op.drop_index('idx_inspections_needs_review', table_name='inspections', postgresql_where=sa.text('needs_review = TRUE'))
    op.create_index(op.f('ix_inspections_status'), 'inspections', ['status'], unique=False)
    op.create_index(op.f('ix_inspections_needs_review'), 'inspections', ['needs_review'], unique=False, postgresql_where='(needs_review = true)')
    op.alter_column('inspections', 'verified_json_path',
               existing_type=sa.VARCHAR(length=1024),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('inspections', 'ocr_json_path',
               existing_type=sa.VARCHAR(length=1024),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('inspections', 'image_path_enhanced',
               existing_type=sa.VARCHAR(length=1024),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('inspections', 'image_path_original',
               existing_type=sa.VARCHAR(length=1024),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('inspections', 'image_pipeline_version',
               existing_type=sa.VARCHAR(length=64),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('inspections', 'ai_version',
               existing_type=sa.VARCHAR(length=64),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('inspections', 'ocr_version',
               existing_type=sa.VARCHAR(length=64),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('inspections', 'raw_text',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("''::text"))
    op.alter_column('inspections', 'final_verified_by',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('inspections', 'verified_by',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('inspections', 'line_no',
               existing_type=sa.VARCHAR(length=32),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('inspections', 'shift',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=8),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('inspections', 'inspector',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('inspections', 'chassis_no',
               existing_type=sa.VARCHAR(length=128),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('inspections', 'engine_no',
               existing_type=sa.VARCHAR(length=128),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('inspections', 'tractor_model',
               existing_type=sa.VARCHAR(length=128),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('inspections', 'tractor_no',
               existing_type=sa.VARCHAR(length=64),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('inspections', 'batch_page_index',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('inspections', 'page_number',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('exports', 'created_by',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('duplicate_log', 'operator',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('defect_library', 'manufacturer_context',
               existing_type=sa.VARCHAR(length=512),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('defect_library', 'component',
               existing_type=sa.VARCHAR(length=128),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('defect_library', 'category',
               existing_type=sa.VARCHAR(length=128),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('correction_log', 'operator',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('correction_log', 'corrected_value',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("''::text"))
    op.alter_column('correction_log', 'ocr_value',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("''::text"))
    op.alter_column('batches', 'line_name',
               existing_type=sa.VARCHAR(length=128),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('batches', 'plant_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('batches', 'factory_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('batches', 'image_pipeline_version',
               existing_type=sa.VARCHAR(length=64),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('batches', 'ai_version',
               existing_type=sa.VARCHAR(length=64),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('batches', 'ocr_version',
               existing_type=sa.VARCHAR(length=64),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('batches', 'original_pdf_path',
               existing_type=sa.VARCHAR(length=1024),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('batches', 'scanner_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('batches', 'operator',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    # ### end Alembic commands ###
